# Configuration for fuxingloh/multi-labeler
# https://github.com/fuxingloh/multi-labeler

version: v1

labels:
  # Label for LangSmith documentation changes
  - label: langsmith
    sync: true
    matcher:
      files:
        any:
          - 'src/langsmith/**'

  # Label for LangGraph documentation changes
  - label: langgraph
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/langgraph/**'

  # Label for LangChain documentation changes
  - label: langchain
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/langchain/**'
          - 'src/oss/python/**'
          - 'src/oss/javascript/**'

  # Label for Deep Agents documentation changes
  - label: deepagents
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/deepagents/**'

  # Label for OSS documentation changes
  - label: oss
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/**'

  # Label for Python-specific documentation
  - label: python
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/python/**'
          - '**/*.py'

  # Label for JavaScript-specific documentation
  - label: javascript
    sync: true
    matcher:
      files:
        any:
          - 'src/oss/javascript/**'
          - '**/*.js'
          - '**/*.ts'

  # Label for reference-specific documentation
  - label: reference
    sync: true
    matcher:
      files:
        any:
          - 'reference/**'

  # Label for Python reference-specific documentation
  - label: python-reference
    sync: true
    matcher:
      files:
        any:
          - 'reference/python/**'

  # Label for JS reference-specific documentation
  - label: javascript-reference
    sync: true
    matcher:
      files:
        any:
          - 'reference/javascript/**'

  # Label for build/CI changes
  - label: ci
    sync: true
    matcher:
      files:
        any:
          - '.github/workflows/**'
          - '.github/actions/**'
          - 'Makefile'
          - 'pyproject.toml'
          - 'package.json'
          - 'uv.lock'

  # Label for documentation infrastructure changes
  - label: docs-infra
    sync: true
    matcher:
      files:
        any:
          - 'pipeline/**'
          - 'scripts/**'

  # Label for test changes
  - label: tests
    sync: true
    matcher:
      files:
        any:
          - 'tests/**'
          - '**/*test*.py'
          - '**/*test*.js'
          - '**/*test*.ts'

  # Protected labels - managed by tag-external-contributions.yml
  # sync: false means these labels will NEVER be removed by this action
  - label: internal
    sync: false
    matcher:
      files:
        any:
          - '.github/labeler-protected-internal-never-matches'

  - label: external
    sync: false
    matcher:
      files:
        any:
          - '.github/labeler-protected-external-never-matches'
